### ISSUE TITLE
Command injection attack does not work

### ISSUE THREAD

**Issue by drdavella** [k-tamura/easybuggy4django#3]
It actually looks like the email address is being properly validated by this app, which prevents the command injection attack from working: 

https://github.com/k-tamura/easybuggy4django/blob/01f060efbd186c2794119219f60e33ddceea467b/easybuggy/views.py#L552-L554

It seems like you need to be using a less stringent check for the email address in order for this attack to work.

It's kind of funny to ask you to make your app more vulnerable 😆

**Comment by k-tamura** [comment]
@drdavella 

Oops, I messed up. `validate_email()` is not needed as you said.

Thank you!
